### ISSUE TITLE
Poprawa błędu niepoprawnych wyników zwracanych z bazy

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [bartlomiej-szlachta/Kinowy-system-rezerwacji#49]
Metoda `internal List<RezerwacjaEntity> FindAllBySeansId(int idSeansu)` od pewnego czasu (tzn od któregoś mojego commita) zwraca w odpowiedzi pustą listę. Musimy obczaić, dlaczego tak jest (ja już nie myślę o tej porze)

**Comment by kamil-rusin** [comment]
pytanie
a na jakie seanse mamy rezerwacje? bo wrzucałem wszystko na przełom czerwca, więc możemy trafić na pusty seans :/

**Comment by kamil-rusin** [comment]
O to chodzi? Chyba działa.

![image](https://user-images.githubusercontent.com/48494453/60645231-703e5080-9e38-11e9-8bf9-88b076b16d82.png)
