### ISSUE TITLE
Utworzenie ekranu listy dostępnych seansów

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [bartlomiej-szlachta/Kinowy-system-rezerwacji#9]
Przed rozpoczęciem pracy warto zaciągnąć najnowsze zmiany z mastera.

Ekran byłby wyświetlany po wybraniu dnia (#36)

Ekran powinien umożliwiać wybranie seansu do zarezerwowania. Cały ekran wypadałoby zamknąć w osobnej kontrolce, aby cały był w osobnej klasie. W tej kontrolce można zająć całą powierzchnię jednym elementem (np `Listbox`). Trzeba się tu zastanowić, jak rozwiązać problem wywoływania akcji wyboru tego seansu - button? podwójne kliknięcie? jeśli button, to gdzie? Mogą się tu przydać bardziej rozbudowane komponenty, jak `ListView`, albo `DataGridView`?

Do testowania można sobie zmodyfikować klasę `Program`, lub użyć funkcjonalności z modelu, utworzonej w #33.

Planowane wdrażanie: 1 / 2 lipca

**Comment by bartlomiej-szlachta** [comment]
Zaktualizowałem opis

**Comment by kamil-rusin** [comment]
Ma być tak:
![image](https://user-images.githubusercontent.com/48494453/60614283-ed33e080-9dcc-11e9-9d74-38f3bf27c2fc.png)

A jest tak(dla testów narzucone na istniejącą kontrolkę):
![image](https://user-images.githubusercontent.com/48494453/60614353-03da3780-9dcd-11e9-8d52-3e3b96f027d5.png)
